app:
  name: bluebell
  mode: dev
  port: 8080
  version: v0.0.1
  locale: zh
  start_time: 2021-04-16
  machine_id: 1

log:
  level: debug
  filename: web_app.log
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbname: sql_demo
  max_open_conns: 200
  max_idel_conns: 50

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  poll_size: 20

