port: 8081

version: "0.1"

mysql:
  host: "192.168.23.169"
  port: 3306
  user: "root"
  password: "123456789"
  dbname: "BigData"

memcache:
  port: "9425"

diskcache:
  port: 9425
  cacheDir: "/home/eintr/Share/rocksdb"

