Server:
  Port: 8081

Cache:
  CacheType: mem
  Port: 9425
  TTL: 10
  CacheDir: /home/yixingwei/Share/rocksdb

Database:
  Host: 192.168.23.169
  Port: 3306
  User: root
  Password: 123456789
  DBname: BigData
